### ISSUE TITLE
Address concerns with section 3

### ISSUE THREAD

**Issue by danvangeest** [x509-hbs/draft-x509-shbs#11]
During WGLC for version -04, Michael, Russ and Corey all had concerns about Section 3, "Use Cases of S-HBS in X.509":
https://mailarchive.ietf.org/arch/msg/spasm/4CjuMTStnQ7GDKNtLd3c4FYXXPU/
https://mailarchive.ietf.org/arch/msg/spasm/7rQTh7xPLDMckPCRjIrUakskI20/
https://mailarchive.ietf.org/arch/msg/spasm/HDYrwCYUZqvHI-lPAYsY7Ohd0c0/

That section was added in draft-gazdag-x509-hash-sigs-02.

Is it necessary to have this section?

If yes, is it necessary to have normative language in this section or should such restrictions be left to certificate policy?  Normative language may be too restrictive and not cover potentially valid use cases, for example Corey brought up the case of CRL issuer certificates. Should we instead refer to some example policies (NIST, BSI?).

**Comment by BashiriK** [comment]
We added this section, since some people on the forum asked us to do so. I think it was Panos. The problem was that they said that we should include this section as using stateful schemes can lead to many dangerous situations which should be taken care of. 

I think one solution could be that we avoid normative language. This seems like a middle way to me. What do you think?

**Comment by BashiriK** [comment]
In other words: Let's keep this section but let's get rid of normative language.

**Comment by fluppe2** [comment]
What @BashiriK is referring to as the background of why section 3 has been formulated can be found here: https://mailarchive.ietf.org/arch/msg/spasm/3XiW2VUdPN2It_0ToyqHQssnfL0/
